import {
  Activity,
  AlertTriangle,
  Archive,
  BadgeCheck,
  BarChart3,
  Bell,
  Building2,
  CalendarClock,
  ClipboardCheck,
  Database,
  FileCheck2,
  FileText,
  FolderOpen,
  Gauge,
  HelpCircle,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Settings,
  ShieldAlert,
  ShieldCheck,
  UserCog,
  Wrench,
  type LucideIcon
} from "lucide-react";

import type { IconName } from "@/lib/dashboard-data";

export const iconMap: Record<IconName, LucideIcon> = {
  Activity,
  AlertTriangle,
  Archive,
  BadgeCheck,
  BarChart3,
  Bell,
  Building2,
  CalendarClock,
  ClipboardCheck,
  Database,
  FileCheck2,
  FileText,
  FolderOpen,
  Gauge,
  HelpCircle,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Settings,
  ShieldAlert,
  ShieldCheck,
  UserCog,
  Wrench
};
